include $(sort $(wildcard $(BR2_EXTERNAL_LITEX_VEXIIRISCV_PATH)/package/*/*.mk))

ifeq ($(BR2_PACKAGE_VEXIIRISCV_AES),y)
LIBOPENSSL_CFLAGS+=-DVEXIIRISCV_AES
LIBRESSL_CONF_OPTS+=-DVEXIIRISCV_AES=ON
endif

